// GENERATED SAVED-CONFIG POWER HELPERS - do not edit by hand
// Generated by scripts/build.py from product/v2/card_contract.json.
#pragma once

template<typename Config, typename OptionHook>
inline bool normalize_saved_config_power(Config &config, OptionHook normalize_options) {
  if (config.type != "power") return false;
    if (config.label.empty()) config.label = "Power Dashboard";
    if (config.icon.empty()) config.icon = "Auto";
    config.icon_on = "Auto";
    config.sensor.clear();
    config.unit.clear();
    config.type = "power";
    if (config.precision != "" && config.precision != "0" && config.precision != "1" && config.precision != "2") config.precision = "";
  config.options = normalize_options(config.options);
  return true;
}
